# Generated by Django 5.2.8 on 2025-12-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_recruiterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
